WorkoutConstants = {
  WORKOUTS_RECEIVED: "WORKOUTS_RECEIVED",
  CURRENT_USER: "CURRENT_USER",
  NEW_WORKOUT: "NEW_WORKOUT",
  UPDATE_USER: "UPDATE_USER",
  LOGGED_OUT: "LOGGED_OUT",
  CURRENT_USER_TOTALS: "CURRENT_USER_TOTALS"
};

module.exports = WorkoutConstants;
