WorkoutConstants = {
  WORKOUTS_RECEIVED: "WORKOUTS_RECEIVED",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",
  NEW_WORKOUT: "NEW_WORKOUT",
  UPDATE_USER: "UPDATE_USER",
  LOGGED_OUT: "LOGGED_OUT",
  CURRENT_USER_TOTALS: "CURRENT_USER_TOTALS",
  USER_TOTALS: "USER_TOTALS",
  RECEIVE_USER: "RECEIVE_USER",
  ADD_FOLLOWINGS: "ADD_FOLLOWINGS",
  REMOVE_FOLLOWING: "REMOVE_FOLLOWING"
};

module.exports = WorkoutConstants;
